### PR TITLE
Prevent null pointer exception in docker workflow plugin

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Prevent null pointer exception in docker workflow plugin

A method that expects a non-null `job` argument was being passed a null `job` argument.  Now returns an empty list when a null `job` is passed.

This will need to be released so that this plugin can be included in the Jenkins plugin bill of materials.  More details are available at:

* https://github.com/jenkinsci/bom/issues/2439

This pull request should be merged after the merge of:

* #43 

### Testing done

Confirmed that `DockerHubTriggerTest` fails before this change and passes after the change.  Command is:

```bash
mvn clean -Dtest=DockerHubTriggerTest verify
```

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by MarkEWaite** [comment]
@rsandell this is ready for your review.  It would be nice if the following pull requests were merged before this one.

* #42 
* #43

**Review by rsandell — APPROVED** [review]

**Comment by rsandell** [comment]
Please remind me on Monday to make a release unless someone makes a release before that 😊

**Comment by MarkEWaite** [comment]
> Please remind me on Monday to make a release unless someone makes a release before that 😊

Will do.  Thanks very much for merging the change.  I'll use an incremental build from the master branch of this plugin to run a final test of the inclusion in the plugin bill of materials.  I won't start that evaluation test until the currently running plugin BOM tests are complete.

**Comment by MarkEWaite** [comment]
> I'll use an incremental build from the master branch of this plugin to run a final test of the inclusion in the plugin bill of materials

@rsandell, the [plugin bill of materials draft evaluation](https://github.com/jenkinsci/bom/pull/2595) of the master branch incremental build was successful.  Not a rush, but the next release of the dockerhub-notification will allow it to be added to the plugin bill of materials so that it will be tested in combination with other plugins.

**Pull request merged**
