### PR TITLE
[JENKINS-74202] [JENKINS-74203] Use updated Jenkins core tags

### PR DESCRIPTION
**Pull request by shlomomdahan**
This PR was initially intended to fix some inline onClick tags in `optionalBlock.jelly` and `expandableTextbox.jelly`, however, it seems like the best approach here is to remove the tag overrides as they are outdated.

### Problem
1. Inline onClick tags need to be removed in `optionalBlock.jelly` and `expandableTextbox.jelly`. to comply with CSP. 
2. Noticed that these are files which overwrite the core implementations of these tags were probably created to fix some stylistic issues as described in: https://github.com/jenkinsci/dockerhub-notification-plugin/pull/23
3. As of Jenkins 2.277.1, table layout is no longer used in the forms. [Table to div layout migration](https://www.jenkins.io/doc/developer/views/table-to-div-migration/#table-to-div-layout-migration)

### Concerns 
1. As shown in the below screenshot, there are around ~8% (~127 users) who are using the plugin while running Jenkins `< 2.771.2`
Screenshot 2024-11-12 at 4 03 38 PM

### Solution
1. Delete and remove all references to these local files which override the tag implementations in core. 
3. As of [Jenkins 2.771.1](https://www.jenkins.io/changelog-stable/2.277.1/) table layout forms are no longer used. 
4. #23 was merged on Jun 24, 2020 while Jenkins 2.771.1 was released on March 10, 2021.
5. As of  [Jenkins 2.361](https://www.jenkins.io/changelog-stable/#v2.361.1) inline onClick handlers in the above files have already been addressed.  [Relevant commit](https://github.com/jenkinsci/jenkins/commit/fb7941cd32fb8f1e757193580833a733056a0978#diff-10922aee3260853be495a09cf3bf13bf5f931bc128e334807e3008ff00b57651R1299)
6. Minimum Jenkins version required to run this plugin is [2.414.3](https://www.jenkins.io/changelog-stable/2.414.3/)

### Testing done
Tested manually and confirmed there are no changes in functionality.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by basil** [comment]
@rsandell Are you interested in performing a release of this? If not, I can begin the adoption process.

**Comment by rsandell** [comment]
@basil you should already have permissions to release: https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-dockerhub-notification.yml#L10
?

**Comment by rsandell** [comment]
But I am on it.

**Comment by basil** [comment]
Thanks!

**Pull request merged**
